### PR TITLE
Request to merge Milestone 5 with development branch

### PR DESCRIPTION
**Pull request by mohamednaser**
Dear Reviewer 

I have finished tasks related to milestone 5 and asking for merge with the development branch 

thanks in advance for your time and efforts

### CODE REVIEW

**Review by maelfosso — CHANGES_REQUESTED** [review]
# Changes required :red_circle: 

Hello @mohamednaser 

Thank you for the app. Before moving forward, there is some changes to should do.

1. Please, to send a friendship request, we should open the user's show page, in the users' list, you should add a link for sending the friendship request, as required [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png)

2. Your timeline contains all the posts whereas it's [required here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/friends_timeline.png) that posts timeline includes posts written by logged-in user and their friend

3. Please, in your `friendshiprequest` table, you should set to `false` the status when Alice send a friendship request to Bob.

4. There is no link for removing or cancelling a friendship request you sent. And there is also no link to reject a friendship request someone sent you.

5. There is a weird bug I notice. Bob send a friendship request to Alice. Alice signed in and accept the friendship request. But what is weird is, when Alice open the Bob's profile, **there is a `send Friendship Request` link**. 
You could notice the result here, what is happening is the FriendshipsRequest table when I click on the link
```ruby
2.7.0 :001 > FriendshipsRequest.all
  FriendshipsRequest Load (2.0ms)  SELECT  "friendships_requests".* FROM "friendships_requests" LIMIT $1  [["LIMIT", 11]]
 => #<ActiveRecord::Relation [#<FriendshipsRequest id: 1, user_id: 2, friend_id: 1, status: true, created_at: "2020-02-25 07:48:09", updated_at: "2020-02-25 07:52:46">, #<FriendshipsRequest id: 2, user_id: 1, friend_id: 2, status: nil, created_at: "2020-02-25 07:55:39", updated_at: "2020-02-25 07:55:39">]> 
2.7.0 :002 > 
```
You could notice the second line from `User 1` to `User 2` while there is already a friendship connection between `User 2` and `User 1`.
You should avoid it.


Kindly fix the suggested changes and submit a new code review request.
Thanks

Mael FOSSO

**Comment by samgaco** [comment]
Hi @mohamednaser :high_brightness: 

From the previous review, these points are still to be implemented:

- [x] > Please, to send a friendship request, we should open the user's show page, in the users' list, you should add a link for sending the friendship request, as required [here](https://gitlab.com/microverse/guides/projects/requirements_screenshots/raw/master/images/rails/final_project/milestone5/user_can_see_invite_buttton.png)


This is still not implemented. The invitation is seen on the user's show page but not on the user list. (Image related)

lisstnoinvt


- [x] > Your timeline contains all the posts whereas it's required here that posts timeline includes posts written by logged-in user and their friend


A user can see posts of a user without those users being his friends, and that should not be happening.


Please, work on those and submit back for another review :+1: 

Regards!

------------------------

* ###### STATUS OF THE MILESTONE: REQUESTED CHANGES :stop_sign:

**Comment by samgaco** [comment]
Hi @mohamednaser :high_brightness: 

Well done, you can continue :+1: 

------------

* ###### STATUS OF THE MILESTONE: APPROVED :heavy_check_mark:

**Comment by Israel-Laguan** [comment]
In the model for User, I see a space for `gravatar_url`
https://github.com/mohamednaser/ror-social-scaffold/blob/48e7cb9e2b8f4f19158beaca9333a4ecc94b9de0/db/schema.rb#L68

But in the view, I don't see an implementation of this

https://github.com/mohamednaser/ror-social-scaffold/blob/milestone_5/app/views/users/show.html.erb

Nor in the Posts or in Friend request. 

Will you implement it later?

**Comment by Israel-Laguan** [comment]
Seems like the code inside these files have the same code repeated

image

https://github.com/mohamednaser/ror-social-scaffold/blob/48e7cb9e2b8f4f19158beaca9333a4ecc94b9de0/app/helpers/friendships_request_helper.rb#L2-L6

I am missing something? Or it can be improved/moved?

**Comment by JuanPabloGil** [comment]
On Friends Controller you can replace these lines with just one line with a private returning the input.

https://github.com/mohamednaser/ror-social-scaffold/blob/7da52bf405494dba61c283ee2d532319ea4e2aaa/app/controllers/friends_controller.rb#L8-L12

`  @new_friendship_request = Friendship.new(user_id: current_user.id, friend_id: params[:friend_id], confirmed: false )`

**Comment by Israel-Laguan** [comment]
The helper's function have View class definitions inside 
https://github.com/mohamednaser/ror-social-scaffold/blob/48e7cb9e2b8f4f19158beaca9333a4ecc94b9de0/app/helpers/application_helper.rb#L5

Consider passing props from View as params

**Pull request merged**
